title: CT's log
description: > # this means to ignore newlines until "baseurl:"
  CT <br>
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ct3777.github.io" # the base hostname & protocol for your site, e.g. http://example.com


author:
  name: 'T'
  last_name: 'C'
  cv: '/artistscv'
  avatar: '/images/logo_ct_circle.png'
  github_username: ct3777
  email: ttt_c@outlook.com
  #vk_id: id201664979
  #telegram_name: vikapitoshka 
  logo: '/images/logo_ct.png'


# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /:categories/:year/:title.html

plugins:
  - jemoji